[workspace]
members = [
    "backend/shared",
    "backend/graphql",
    "backend/rest",
    "backend/hybrid",
]

[workspace.dependencies]
async-graphql = "7.0.17"
async-graphql-actix-web = "7.0.17"
actix-web = "4.11.0"
tokio = {version = "1.47.1", features = ["full"]}